### ISSUE TITLE
Change use of `round` so that the whole package can be 0.3 compatible again

### ISSUE THREAD

**Issue by WestleyArgentum** [forio/UUID.jl#12]
```julia
julia> UUID.v1()
ERROR: `round` has no method matching round(::Type{Integer}, ::Float64)
 in build_timestamp at /Users/westley/.julia/v0.3/UUID/src/UUID.jl:63
 in v1 at /Users/westley/.julia/v0.3/UUID/src/UUID.jl:113
```

**Comment by IainNZ** [comment]
@WestleyArgentum how hard would this be to do? Its a real bummer it doesn't work, because Benchmarks.jl (unregistered) depends on UUID 0.0.4 but then you can't do comparisons between Julia 0.3 and 0.4...

**Comment by WestleyArgentum** [comment]
It probably wouldn't be hard at all... I'm way behind on things but I will write this down in my list and make an effort to get it done

**Comment by WestleyArgentum** [comment]
most trivial fix ever! yay compat.jl!
